server {
	listen 8443 ssl;
	http2 on;
	server_name warden.brtechlabs.com www.warden.brtechlabs.com;

	ssl_certificate /etc/nginx/certs/vaultwarden/fullchain.pem;
	ssl_certificate_key /etc/nginx/certs/vaultwarden/privkey.pem;
	
	resolver 10.89.9.1 valid=10s;

	location / {
		set $vaultwarden_upstream vaultwarden_server;
		proxy_pass https://$vaultwarden_upstream:443;
		proxy_set_header Host $host;
    		proxy_set_header X-Real-IP $remote_addr;
    		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    		proxy_set_header X-Forwarded-Proto https;
		proxy_ssl_name warden.brtechlabs.com;
    		proxy_http_version 1.1;
    		proxy_set_header Connection "";
    		proxy_buffering off;
	}
}
